import Link from 'next/link';
import { Roboto } from 'next/font/google';
import './globals.css';
import type { Metadata } from 'next';
import ListItem from './components/ListItem';
import { Suspense } from 'react';
import SkeletonItem from './components/SkeletonItem';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Roboto({ subsets: ['latin'], weight: '500' });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const posts = await fetch(
    'https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty&limitToFirst=10&orderBy=%22$key%22'
  ).then((res) => res.json() as Promise<number[]>);

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className=" bg-yellow-400 text-center text-3xl text-black grid place-content-center font-bold tracking-wide py-10">
          Uizard Hackernews
        </header>

        <main className="flex">
          <aside>
            <ul className="w-80">
              {posts.map((id) => (
                <Link key={id} href={`/${id}`}>
                  <Suspense fallback={<SkeletonItem />}>
                    <ListItem id={id} />
                  </Suspense>
                </Link>
              ))}
            </ul>
          </aside>
          <section className="flex items-center basis-10/12">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
